### ISSUE TITLE
[bug] navigation from calls tree does not work if the target call is in an anonymous class

### ISSUE THREAD

**Issue by Decencies** [QuiltMC/enigma#82]
When attempting to navigate to the call declaration of a method, if the declaration is in an inner class, will do nothing.

For example:

Call declarations within `ClassName$<id>` won't be navigated to, whereas those declared in non inner classes will navigate just fine.

![java_a7RtG71J9a](https://user-images.githubusercontent.com/66835910/228896667-1f8be69a-6ed9-4c05-b660-e637bb741c50.gif)

Tested version: `1.7.3`

**Comment by ix0rai** [comment]
I have hunted this down and the issue is actually not inner classes, but *anonymous* classes. Any class where the representation looks like `ClassName$[number]` (`ClassName$1`, `ClassName$8`, etc) will break navigation from the calls tree. That makes this:
a. much less severe
and b. more difficult to fix as well, anonymous classes are a little odd in many ways but I'll look into a fix!

(example: the top navigation here is broken, but the bottom one works)
![image](https://user-images.githubusercontent.com/66223394/229262917-dcfa4e40-8db9-4cc9-b0f4-40344f4d8eb3.png)

**Comment by ix0rai** [comment]
this can be reproduced via `:completeTestGui`, viewing calls on `a()` in class `q` (obfuscated names).

**Comment by SpaceWalkerRS** [comment]
I was able to trace the issue to [this line](https://github.com/QuiltMC/enigma/blob/2fb9f735d817505e406276e49ec8e69bbc2c176e/enigma/src/main/java/cuchaz/enigma/EnigmaProject.java#L154), which makes anonymous and local classes explicitly not navigable. I do not know why this was done, but simply removing that `if` block appears to fix the issue.

**Comment by ix0rai** [comment]
can confirm that that fixes the issue, thanks!.
@ByMartrixx why does [this commit](https://github.com/QuiltMC/enigma/commit/302e2fe28b60b48ff816766182fd8c2c2b1a94ed) introduce that `if` block?

**Comment by ByMartrixx** [comment]
Anonymous classes don't have a declaration entry to navigate to. Local classes do, but we don't have a way to tell them apart (yet). Navigation to entries of these classes don't work because [line 376 of GuiController](https://github.com/QuiltMC/enigma/blob/2fb9f735d817505e406276e49ec8e69bbc2c176e/enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java#L376) checks that the location class entry of a reference is navigable, while it should probably check just the entry or its parent instead

**Comment by SpaceWalkerRS** [comment]
> Anonymous classes don't have a declaration entry to navigate to.

That makes sense. That means the fix I suggested would break if the user managed to make Enigma try to navigate to an anonymous class.

> it should probably check just the entry or its parent instead

Checking the entry itself is probably the best solution IMO. Checking the parent would result in this same bug for methods inside anonymous classes.
